# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.15

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /home/sebastian/Downloads/clion-2019.2.1/bin/cmake/linux/bin/cmake

# The command to remove a file.
RM = /home/sebastian/Downloads/clion-2019.2.1/bin/cmake/linux/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/sebastian/Develop/CRT_filter

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/sebastian/Develop/CRT_filter

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/home/sebastian/Downloads/clion-2019.2.1/bin/cmake/linux/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/home/sebastian/Downloads/clion-2019.2.1/bin/cmake/linux/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/sebastian/Develop/CRT_filter/CMakeFiles /home/sebastian/Develop/CRT_filter/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/sebastian/Develop/CRT_filter/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named SDL_CRT_Filter

# Build rule for target.
SDL_CRT_Filter: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 SDL_CRT_Filter
.PHONY : SDL_CRT_Filter

# fast build rule for target.
SDL_CRT_Filter/fast:
	$(MAKE) -f CMakeFiles/SDL_CRT_Filter.dir/build.make CMakeFiles/SDL_CRT_Filter.dir/build
.PHONY : SDL_CRT_Filter/fast

#=============================================================================
# Target rules for targets named CRT_FILTERS

# Build rule for target.
CRT_FILTERS: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 CRT_FILTERS
.PHONY : CRT_FILTERS

# fast build rule for target.
CRT_FILTERS/fast:
	$(MAKE) -f CMakeFiles/CRT_FILTERS.dir/build.make CMakeFiles/CRT_FILTERS.dir/build
.PHONY : CRT_FILTERS/fast

#=============================================================================
# Target rules for targets named SDL2_CRT_Tests

# Build rule for target.
SDL2_CRT_Tests: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 SDL2_CRT_Tests
.PHONY : SDL2_CRT_Tests

# fast build rule for target.
SDL2_CRT_Tests/fast:
	$(MAKE) -f tests/CMakeFiles/SDL2_CRT_Tests.dir/build.make tests/CMakeFiles/SDL2_CRT_Tests.dir/build
.PHONY : SDL2_CRT_Tests/fast

#=============================================================================
# Target rules for targets named CHAR_ROM_GEN

# Build rule for target.
CHAR_ROM_GEN: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 CHAR_ROM_GEN
.PHONY : CHAR_ROM_GEN

# fast build rule for target.
CHAR_ROM_GEN/fast:
	$(MAKE) -f utils/CMakeFiles/CHAR_ROM_GEN.dir/build.make utils/CMakeFiles/CHAR_ROM_GEN.dir/build
.PHONY : CHAR_ROM_GEN/fast

FMAdecode.o: FMAdecode.cpp.o

.PHONY : FMAdecode.o

# target to build an object file
FMAdecode.cpp.o:
	$(MAKE) -f CMakeFiles/SDL_CRT_Filter.dir/build.make CMakeFiles/SDL_CRT_Filter.dir/FMAdecode.cpp.o
.PHONY : FMAdecode.cpp.o

FMAdecode.i: FMAdecode.cpp.i

.PHONY : FMAdecode.i

# target to preprocess a source file
FMAdecode.cpp.i:
	$(MAKE) -f CMakeFiles/SDL_CRT_Filter.dir/build.make CMakeFiles/SDL_CRT_Filter.dir/FMAdecode.cpp.i
.PHONY : FMAdecode.cpp.i

FMAdecode.s: FMAdecode.cpp.s

.PHONY : FMAdecode.s

# target to generate assembly for a file
FMAdecode.cpp.s:
	$(MAKE) -f CMakeFiles/SDL_CRT_Filter.dir/build.make CMakeFiles/SDL_CRT_Filter.dir/FMAdecode.cpp.s
.PHONY : FMAdecode.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... SDL_CRT_Filter"
	@echo "... rebuild_cache"
	@echo "... CRT_FILTERS"
	@echo "... SDL2_CRT_Tests"
	@echo "... CHAR_ROM_GEN"
	@echo "... FMAdecode.o"
	@echo "... FMAdecode.i"
	@echo "... FMAdecode.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

